### ISSUE TITLE
Add a github action to show the build/test status

### ISSUE THREAD

**Issue by zhenfeng-zhu** [andeya/gust#3]
Thanks for your work, that's great!

Maybe we could add a github action ci in this repo. Like this: 

```
name: Go

on:
  push:
    tags:
    branches:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        stable: false
  
    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Test
      run: make coverage

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: unittests
        verbose: true
```
